[package]
name = "livid"
version = "0.1.0"
authors = ["Zach Banks <zjbanks@gmail.com>"]

[dependencies]
dlopen = "0.1.5"
dlopen_derive = "0.1.3"
inotify = "0.6.1"
nix = "0.12.0"
libc = "0.2"
structopt = "0.2"
